# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: White Pine Academy
description: Static site for White Pine Academy
tagline: 
url: "http://stage.server.com"

# Used so Jekyll outputs the site correctly so Gulp can do what it wants
source: src
destination: serve

keep_files: ['assets']

# Same as the title etc for your site but can instead be
# called by using 'site.author.name' and so on
author:
  name: 
  email: 
  bio: 
  twitter: 

# general setting for Jekyll
googleAnalytics: UA-xxxxx-x-test

# _config.build.yml overwrites these options when you run `gulp build`
# Enables future posts (posts with dates in the future) and drafts
future: true
show_drafts: true

# Only make the last 10 posts so generating isn't slow
limit_posts: 10

# Permalink structure and pagination options
relative_permalinks: true
permalink: pretty
paginate: 3
paginate_path: 'page:num'
excerpt_separator: '<!--more-->'

# Markdown library
markdown: redcarpet
# Markdown library options
redcarpet:
  extensions: ['no_intra_emphasis', 'tables', 'fenced_code_blocks', 'autolink', 'smart',
              'strikethrough', 'superscript', 'underline', 'highlight', 'footnotes']
highlighter: true
